"""Add is_admin field to users table

Revision ID: 025c9c128893
Revises: c444ea846152
Create Date: 2024-09-01 15:50:42.006842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025c9c128893'
down_revision: Union[str, None] = 'c444ea846152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('telegram_payment_charge_id', sa.String(), nullable=True),
    sa.Column('provider_payment_charge_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_provider_payment_charge_id'), 'payments', ['provider_payment_charge_id'], unique=True)
    op.create_index(op.f('ix_payments_telegram_payment_charge_id'), 'payments', ['telegram_payment_charge_id'], unique=True)
    op.add_column('referrals', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('routers', sa.Column('status', sa.String(), nullable=True))
    op.add_column('routers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('routers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('routers', sa.Column('subdomain', sa.String(), nullable=False))
    op.add_column('routers', sa.Column('dns_record_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'routers', ['subdomain'])
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('balance', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'balance')
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'routers', type_='unique')
    op.drop_column('routers', 'dns_record_id')
    op.drop_column('routers', 'subdomain')
    op.drop_column('routers', 'updated_at')
    op.drop_column('routers', 'created_at')
    op.drop_column('routers', 'status')
    op.drop_column('referrals', 'created_at')
    op.drop_index(op.f('ix_payments_telegram_payment_charge_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_payment_charge_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
