"""Add auth_token to Router

Revision ID: 1a8f7517412b
Revises: 3c6299ab8e98
Create Date: 2024-09-19 23:22:09.956094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1a8f7517412b'
down_revision: Union[str, None] = '3c6299ab8e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wp_gla_attribute_mapping_rules')
    op.drop_table('wp_postmeta')
    op.drop_table('wp_term_relationships')
    op.drop_index('slug', table_name='wp_wc_tax_rate_classes', mysql_length={'slug': 191})
    op.drop_table('wp_wc_tax_rate_classes')
    op.drop_index('min_max_price', table_name='wp_wc_product_meta_lookup')
    op.drop_table('wp_wc_product_meta_lookup')
    op.drop_table('wp_woocommerce_attribute_taxonomies')
    op.drop_table('wp_woocommerce_tax_rates')
    op.drop_index('download_order_key_product', table_name='wp_woocommerce_downloadable_product_permissions', mysql_length={'order_key': 16})
    op.drop_index('download_order_product', table_name='wp_woocommerce_downloadable_product_permissions')
    op.drop_index('user_order_remaining_expires', table_name='wp_woocommerce_downloadable_product_permissions')
    op.drop_table('wp_woocommerce_downloadable_product_permissions')
    op.drop_table('wp_wc_order_stats')
    op.drop_index('meta_key_value', table_name='wp_wc_orders_meta', mysql_length={'meta_key': 100, 'meta_value': 82})
    op.drop_index('order_id_meta_key_meta_value', table_name='wp_wc_orders_meta', mysql_length={'meta_key': 100, 'meta_value': 82})
    op.drop_table('wp_wc_orders_meta')
    op.drop_table('wp_wc_webhooks')
    op.drop_table('wp_wc_category_lookup')
    op.drop_index('address_type_order_id', table_name='wp_wc_order_addresses')
    op.drop_table('wp_wc_order_addresses')
    op.drop_table('wp_gla_shipping_rates')
    op.drop_table('wp_actionscheduler_groups')
    op.drop_table('wp_links')
    op.drop_index('rate_limit_key', table_name='wp_wc_rate_limits', mysql_length={'rate_limit_key': 191})
    op.drop_table('wp_wc_rate_limits')
    op.drop_table('wp_woocommerce_shipping_zones')
    op.drop_table('wp_commentmeta')
    op.drop_table('wp_woocommerce_payment_tokens')
    op.drop_table('wp_woocommerce_log')
    op.drop_index('customer_id_billing_email', table_name='wp_wc_orders', mysql_length={'billing_email': 171})
    op.drop_index('date_created', table_name='wp_wc_orders')
    op.drop_index('date_updated', table_name='wp_wc_orders')
    op.drop_index('type_status_date', table_name='wp_wc_orders')
    op.drop_table('wp_wc_orders')
    op.drop_table('wp_wc_reserved_stock')
    op.drop_index('term_id_taxonomy', table_name='wp_term_taxonomy')
    op.drop_table('wp_term_taxonomy')
    op.drop_table('wp_wc_order_coupon_lookup')
    op.drop_index('user_login_key', table_name='wp_users')
    op.drop_table('wp_users')
    op.drop_table('wp_actionscheduler_claims')
    op.drop_table('wp_gla_merchant_issues')
    op.drop_table('wp_terms')
    op.drop_index('country_currency', table_name='wp_gla_budget_recommendations')
    op.drop_table('wp_gla_budget_recommendations')
    op.drop_table('wp_wc_order_tax_lookup')
    op.drop_table('wp_wc_admin_note_actions')
    op.drop_index('session_key', table_name='wp_woocommerce_sessions')
    op.drop_table('wp_woocommerce_sessions')
    op.drop_index('type_status_date', table_name='wp_posts')
    op.drop_table('wp_posts')
    op.drop_index('order_id', table_name='wp_wc_order_operational_data')
    op.drop_table('wp_wc_order_operational_data')
    op.drop_table('wp_wc_admin_notes')
    op.drop_index('claim_id_status_scheduled_date_gmt', table_name='wp_actionscheduler_actions')
    op.drop_index('hook_status_scheduled_date_gmt', table_name='wp_actionscheduler_actions', mysql_length={'hook': 163})
    op.drop_index('status_scheduled_date_gmt', table_name='wp_actionscheduler_actions')
    op.drop_table('wp_actionscheduler_actions')
    op.drop_table('wp_usermeta')
    op.drop_index('comment_approved_date_gmt', table_name='wp_comments')
    op.drop_index('woo_idx_comment_type', table_name='wp_comments')
    op.drop_table('wp_comments')
    op.drop_table('wp_actionscheduler_logs')
    op.drop_index('is_variation_attribute_term_id', table_name='wp_wc_product_attributes_lookup')
    op.drop_table('wp_wc_product_attributes_lookup')
    op.drop_index('option_name', table_name='wp_options')
    op.drop_table('wp_options')
    op.drop_table('wp_woocommerce_order_items')
    op.drop_index('location_type_code', table_name='wp_woocommerce_shipping_zone_locations', mysql_length={'location_type': 10, 'location_code': 20})
    op.drop_table('wp_woocommerce_shipping_zone_locations')
    op.drop_table('wp_termmeta')
    op.drop_table('wp_woocommerce_order_itemmeta')
    op.drop_table('wp_woocommerce_payment_tokenmeta')
    op.drop_index('user_id', table_name='wp_wc_customer_lookup')
    op.drop_table('wp_wc_customer_lookup')
    op.drop_table('wp_wc_download_log')
    op.drop_table('wp_woocommerce_shipping_zone_methods')
    op.drop_table('wp_gla_shipping_times')
    op.drop_table('wp_woocommerce_api_keys')
    op.drop_table('wp_wc_order_product_lookup')
    op.drop_index('location_type_code', table_name='wp_woocommerce_tax_rate_locations', mysql_length={'location_type': 10, 'location_code': 20})
    op.drop_table('wp_woocommerce_tax_rate_locations')
    op.add_column('routers', sa.Column('auth_token', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'routers', ['auth_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routers', type_='unique')
    op.drop_column('routers', 'auth_token')
    op.create_table('wp_woocommerce_tax_rate_locations',
    sa.Column('location_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('location_code', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=False),
    sa.Column('tax_rate_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('location_type', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=40), nullable=False),
    sa.PrimaryKeyConstraint('location_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('location_type_code', 'wp_woocommerce_tax_rate_locations', ['location_type', 'location_code'], unique=False, mysql_length={'location_type': 10, 'location_code': 20})
    op.create_table('wp_wc_order_product_lookup',
    sa.Column('order_item_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('variation_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('customer_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('date_created', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('product_qty', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_net_revenue', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=False),
    sa.Column('product_gross_revenue', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=False),
    sa.Column('coupon_amount', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=False),
    sa.Column('tax_amount', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=False),
    sa.Column('shipping_amount', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=False),
    sa.Column('shipping_tax_amount', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=False),
    sa.PrimaryKeyConstraint('order_item_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_woocommerce_api_keys',
    sa.Column('key_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=True),
    sa.Column('permissions', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=10), nullable=False),
    sa.Column('consumer_key', mysql.CHAR(collation='utf8mb4_unicode_520_ci', length=64), nullable=False),
    sa.Column('consumer_secret', mysql.CHAR(collation='utf8mb4_unicode_520_ci', length=43), nullable=False),
    sa.Column('nonces', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.Column('truncated_key', mysql.CHAR(collation='utf8mb4_unicode_520_ci', length=7), nullable=False),
    sa.Column('last_access', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('key_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_gla_shipping_times',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('country', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=2), nullable=False),
    sa.Column('time', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_woocommerce_shipping_zone_methods',
    sa.Column('zone_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('instance_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('method_id', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=False),
    sa.Column('method_order', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('is_enabled', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('instance_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_wc_download_log',
    sa.Column('download_log_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('permission_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('user_ip_address', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), server_default=sa.text("''"), nullable=True),
    sa.PrimaryKeyConstraint('download_log_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_wc_customer_lookup',
    sa.Column('customer_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), nullable=True),
    sa.Column('date_last_active', mysql.TIMESTAMP(), nullable=True),
    sa.Column('date_registered', mysql.TIMESTAMP(), nullable=True),
    sa.Column('country', mysql.CHAR(collation='utf8mb4_unicode_520_ci', length=2), server_default=sa.text("''"), nullable=False),
    sa.Column('postcode', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("''"), nullable=False),
    sa.Column('city', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('state', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('customer_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'wp_wc_customer_lookup', ['user_id'], unique=True)
    op.create_table('wp_woocommerce_payment_tokenmeta',
    sa.Column('meta_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('payment_token_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('meta_key', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=True),
    sa.Column('meta_value', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.PrimaryKeyConstraint('meta_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_woocommerce_order_itemmeta',
    sa.Column('meta_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('order_item_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('meta_key', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=True),
    sa.Column('meta_value', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.PrimaryKeyConstraint('meta_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_termmeta',
    sa.Column('meta_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('term_id', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('meta_key', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=True),
    sa.Column('meta_value', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.PrimaryKeyConstraint('meta_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_woocommerce_shipping_zone_locations',
    sa.Column('location_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('zone_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('location_code', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=False),
    sa.Column('location_type', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=40), nullable=False),
    sa.PrimaryKeyConstraint('location_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('location_type_code', 'wp_woocommerce_shipping_zone_locations', ['location_type', 'location_code'], unique=False, mysql_length={'location_type': 10, 'location_code': 20})
    op.create_table('wp_woocommerce_order_items',
    sa.Column('order_item_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('order_item_name', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('order_item_type', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('order_item_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_options',
    sa.Column('option_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('option_name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=191), server_default=sa.text("''"), nullable=False),
    sa.Column('option_value', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('autoload', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("'yes'"), nullable=False),
    sa.PrimaryKeyConstraint('option_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('option_name', 'wp_options', ['option_name'], unique=True)
    op.create_table('wp_wc_product_attributes_lookup',
    sa.Column('product_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('product_or_parent_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('taxonomy', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=32), nullable=False),
    sa.Column('term_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_variation_attribute', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('in_stock', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('product_or_parent_id', 'term_id', 'product_id', 'taxonomy'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('is_variation_attribute_term_id', 'wp_wc_product_attributes_lookup', ['is_variation_attribute', 'term_id'], unique=False)
    op.create_table('wp_actionscheduler_logs',
    sa.Column('log_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('action_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('message', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('log_date_gmt', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=True),
    sa.Column('log_date_local', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=True),
    sa.PrimaryKeyConstraint('log_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_comments',
    sa.Column('comment_ID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('comment_post_ID', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('comment_author', mysql.TINYTEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('comment_author_email', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('comment_author_url', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('comment_author_IP', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('comment_date', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('comment_date_gmt', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('comment_content', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('comment_karma', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('comment_approved', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("'1'"), nullable=False),
    sa.Column('comment_agent', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('comment_type', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("'comment'"), nullable=False),
    sa.Column('comment_parent', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('comment_ID'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('woo_idx_comment_type', 'wp_comments', ['comment_type'], unique=False)
    op.create_index('comment_approved_date_gmt', 'wp_comments', ['comment_approved', 'comment_date_gmt'], unique=False)
    op.create_table('wp_usermeta',
    sa.Column('umeta_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('meta_key', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=True),
    sa.Column('meta_value', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.PrimaryKeyConstraint('umeta_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_actionscheduler_actions',
    sa.Column('action_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('hook', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=191), nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), nullable=False),
    sa.Column('scheduled_date_gmt', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=True),
    sa.Column('scheduled_date_local', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=True),
    sa.Column('priority', mysql.TINYINT(unsigned=True), server_default=sa.text("'10'"), autoincrement=False, nullable=False),
    sa.Column('args', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=191), nullable=True),
    sa.Column('schedule', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.Column('group_id', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('attempts', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('last_attempt_gmt', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=True),
    sa.Column('last_attempt_local', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=True),
    sa.Column('claim_id', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('extended_args', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=8000), nullable=True),
    sa.PrimaryKeyConstraint('action_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('status_scheduled_date_gmt', 'wp_actionscheduler_actions', ['status', 'scheduled_date_gmt'], unique=False)
    op.create_index('hook_status_scheduled_date_gmt', 'wp_actionscheduler_actions', ['hook', 'status', 'scheduled_date_gmt'], unique=False, mysql_length={'hook': 163})
    op.create_index('claim_id_status_scheduled_date_gmt', 'wp_actionscheduler_actions', ['claim_id', 'status', 'scheduled_date_gmt'], unique=False)
    op.create_table('wp_wc_admin_notes',
    sa.Column('note_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), nullable=False),
    sa.Column('locale', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), nullable=False),
    sa.Column('title', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('content', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('content_data', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=False),
    sa.Column('source', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('date_reminder', mysql.DATETIME(), nullable=True),
    sa.Column('is_snoozable', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('layout', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("''"), nullable=False),
    sa.Column('image', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('icon', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), server_default=sa.text("'info'"), nullable=False),
    sa.PrimaryKeyConstraint('note_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_wc_order_operational_data',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('created_via', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), nullable=True),
    sa.Column('woocommerce_version', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), nullable=True),
    sa.Column('prices_include_tax', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('coupon_usages_are_counted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('download_permission_granted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('cart_hash', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), nullable=True),
    sa.Column('new_order_email_sent', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('order_key', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), nullable=True),
    sa.Column('order_stock_reduced', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('date_paid_gmt', mysql.DATETIME(), nullable=True),
    sa.Column('date_completed_gmt', mysql.DATETIME(), nullable=True),
    sa.Column('shipping_tax_amount', mysql.DECIMAL(precision=26, scale=8), nullable=True),
    sa.Column('shipping_total_amount', mysql.DECIMAL(precision=26, scale=8), nullable=True),
    sa.Column('discount_tax_amount', mysql.DECIMAL(precision=26, scale=8), nullable=True),
    sa.Column('discount_total_amount', mysql.DECIMAL(precision=26, scale=8), nullable=True),
    sa.Column('recorded_sales', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('order_id', 'wp_wc_order_operational_data', ['order_id'], unique=True)
    op.create_table('wp_posts',
    sa.Column('ID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('post_author', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('post_date', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('post_date_gmt', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('post_content', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('post_title', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('post_excerpt', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('post_status', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("'publish'"), nullable=False),
    sa.Column('comment_status', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("'open'"), nullable=False),
    sa.Column('ping_status', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("'open'"), nullable=False),
    sa.Column('post_password', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('post_name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('to_ping', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('pinged', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('post_modified', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('post_modified_gmt', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('post_content_filtered', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('post_parent', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('guid', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('menu_order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('post_type', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("'post'"), nullable=False),
    sa.Column('post_mime_type', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('comment_count', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('type_status_date', 'wp_posts', ['post_type', 'post_status', 'post_date', 'ID'], unique=False)
    op.create_table('wp_woocommerce_sessions',
    sa.Column('session_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('session_key', mysql.CHAR(collation='utf8mb4_unicode_520_ci', length=32), nullable=False),
    sa.Column('session_value', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('session_expiry', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('session_key', 'wp_woocommerce_sessions', ['session_key'], unique=True)
    op.create_table('wp_wc_admin_note_actions',
    sa.Column('action_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('note_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=False),
    sa.Column('label', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=False),
    sa.Column('query', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=False),
    sa.Column('actioned_text', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=False),
    sa.Column('nonce_action', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=True),
    sa.Column('nonce_name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('action_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_wc_order_tax_lookup',
    sa.Column('order_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('tax_rate_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('date_created', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('shipping_tax', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=False),
    sa.Column('order_tax', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=False),
    sa.Column('total_tax', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=False),
    sa.PrimaryKeyConstraint('order_id', 'tax_rate_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_gla_budget_recommendations',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('currency', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=3), nullable=False),
    sa.Column('country', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=2), nullable=False),
    sa.Column('daily_budget', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('country_currency', 'wp_gla_budget_recommendations', ['country', 'currency'], unique=True)
    op.create_table('wp_terms',
    sa.Column('term_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('slug', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('term_group', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('term_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_gla_merchant_issues',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('issue', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), nullable=False),
    sa.Column('severity', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("'warning'"), nullable=False),
    sa.Column('product', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), nullable=False),
    sa.Column('action', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('action_url', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=1024), nullable=False),
    sa.Column('applicable_countries', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('source', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=10), server_default=sa.text("'mc'"), nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=10), server_default=sa.text("'product'"), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_actionscheduler_claims',
    sa.Column('claim_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('date_created_gmt', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=True),
    sa.PrimaryKeyConstraint('claim_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_users',
    sa.Column('ID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_login', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('user_pass', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('user_nicename', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('user_email', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('user_url', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('user_registered', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_activation_key', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('user_status', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('display_name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=250), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_login_key', 'wp_users', ['user_login'], unique=False)
    op.create_table('wp_wc_order_coupon_lookup',
    sa.Column('order_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('coupon_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('date_created', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('discount_amount', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=False),
    sa.PrimaryKeyConstraint('order_id', 'coupon_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_term_taxonomy',
    sa.Column('term_taxonomy_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('term_id', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('taxonomy', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('description', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('parent', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('count', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('term_taxonomy_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('term_id_taxonomy', 'wp_term_taxonomy', ['term_id', 'taxonomy'], unique=True)
    op.create_table('wp_wc_reserved_stock',
    sa.Column('order_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('stock_quantity', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('expires', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.PrimaryKeyConstraint('order_id', 'product_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_wc_orders',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), nullable=True),
    sa.Column('currency', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=10), nullable=True),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), nullable=True),
    sa.Column('tax_amount', mysql.DECIMAL(precision=26, scale=8), nullable=True),
    sa.Column('total_amount', mysql.DECIMAL(precision=26, scale=8), nullable=True),
    sa.Column('customer_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('billing_email', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=320), nullable=True),
    sa.Column('date_created_gmt', mysql.DATETIME(), nullable=True),
    sa.Column('date_updated_gmt', mysql.DATETIME(), nullable=True),
    sa.Column('parent_order_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('payment_method', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), nullable=True),
    sa.Column('payment_method_title', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.Column('transaction_id', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), nullable=True),
    sa.Column('user_agent', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.Column('customer_note', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('type_status_date', 'wp_wc_orders', ['type', 'status', 'date_created_gmt'], unique=False)
    op.create_index('date_updated', 'wp_wc_orders', ['date_updated_gmt'], unique=False)
    op.create_index('date_created', 'wp_wc_orders', ['date_created_gmt'], unique=False)
    op.create_index('customer_id_billing_email', 'wp_wc_orders', ['customer_id', 'billing_email'], unique=False, mysql_length={'billing_email': 171})
    op.create_table('wp_woocommerce_log',
    sa.Column('log_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('level', mysql.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('source', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=False),
    sa.Column('message', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('context', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.PrimaryKeyConstraint('log_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_woocommerce_payment_tokens',
    sa.Column('token_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('gateway_id', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=False),
    sa.Column('token', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=False),
    sa.Column('is_default', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('token_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_commentmeta',
    sa.Column('meta_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('comment_id', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('meta_key', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=True),
    sa.Column('meta_value', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.PrimaryKeyConstraint('meta_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_woocommerce_shipping_zones',
    sa.Column('zone_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('zone_name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=False),
    sa.Column('zone_order', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('zone_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_wc_rate_limits',
    sa.Column('rate_limit_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('rate_limit_key', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=False),
    sa.Column('rate_limit_expiry', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('rate_limit_remaining', mysql.SMALLINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('rate_limit_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('rate_limit_key', 'wp_wc_rate_limits', ['rate_limit_key'], unique=True, mysql_length={'rate_limit_key': 191})
    op.create_table('wp_links',
    sa.Column('link_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('link_url', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('link_name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('link_image', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('link_target', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=25), server_default=sa.text("''"), nullable=False),
    sa.Column('link_description', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('link_visible', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("'Y'"), nullable=False),
    sa.Column('link_owner', mysql.BIGINT(unsigned=True), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('link_rating', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('link_updated', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('link_rel', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('link_notes', mysql.MEDIUMTEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('link_rss', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('link_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_actionscheduler_groups',
    sa.Column('group_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('slug', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=False),
    sa.PrimaryKeyConstraint('group_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_gla_shipping_rates',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('country', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=2), nullable=False),
    sa.Column('currency', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=3), nullable=False),
    sa.Column('rate', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=False),
    sa.Column('options', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_wc_order_addresses',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('address_type', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), nullable=True),
    sa.Column('first_name', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.Column('last_name', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.Column('company', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.Column('address_1', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.Column('address_2', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.Column('city', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.Column('state', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.Column('postcode', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.Column('country', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=320), nullable=True),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('address_type_order_id', 'wp_wc_order_addresses', ['address_type', 'order_id'], unique=True)
    op.create_table('wp_wc_category_lookup',
    sa.Column('category_tree_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('category_tree_id', 'category_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_wc_webhooks',
    sa.Column('webhook_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=False),
    sa.Column('name', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('delivery_url', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('secret', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('topic', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('date_created_gmt', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('date_modified', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('date_modified_gmt', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('api_version', mysql.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('failure_count', mysql.SMALLINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('pending_delivery', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('webhook_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_wc_orders_meta',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('meta_key', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=True),
    sa.Column('meta_value', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('order_id_meta_key_meta_value', 'wp_wc_orders_meta', ['order_id', 'meta_key', 'meta_value'], unique=False, mysql_length={'meta_key': 100, 'meta_value': 82})
    op.create_index('meta_key_value', 'wp_wc_orders_meta', ['meta_key', 'meta_value'], unique=False, mysql_length={'meta_key': 100, 'meta_value': 82})
    op.create_table('wp_wc_order_stats',
    sa.Column('order_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('parent_id', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('date_created', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('date_created_gmt', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('date_paid', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=True),
    sa.Column('date_completed', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=True),
    sa.Column('num_items_sold', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('total_sales', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=False),
    sa.Column('tax_total', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=False),
    sa.Column('shipping_total', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=False),
    sa.Column('net_total', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=False),
    sa.Column('returning_customer', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=False),
    sa.Column('customer_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('order_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_woocommerce_downloadable_product_permissions',
    sa.Column('permission_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('download_id', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=36), nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('order_key', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=False),
    sa.Column('user_email', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('downloads_remaining', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=9), nullable=True),
    sa.Column('access_granted', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('access_expires', mysql.DATETIME(), nullable=True),
    sa.Column('download_count', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('permission_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_order_remaining_expires', 'wp_woocommerce_downloadable_product_permissions', ['user_id', 'order_id', 'downloads_remaining', 'access_expires'], unique=False)
    op.create_index('download_order_product', 'wp_woocommerce_downloadable_product_permissions', ['download_id', 'order_id', 'product_id'], unique=False)
    op.create_index('download_order_key_product', 'wp_woocommerce_downloadable_product_permissions', ['product_id', 'order_id', 'order_key', 'download_id'], unique=False, mysql_length={'order_key': 16})
    op.create_table('wp_woocommerce_tax_rates',
    sa.Column('tax_rate_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tax_rate_country', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=2), server_default=sa.text("''"), nullable=False),
    sa.Column('tax_rate_state', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('tax_rate', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=8), server_default=sa.text("''"), nullable=False),
    sa.Column('tax_rate_name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('tax_rate_priority', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('tax_rate_compound', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('tax_rate_shipping', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('tax_rate_order', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('tax_rate_class', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('tax_rate_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_woocommerce_attribute_taxonomies',
    sa.Column('attribute_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('attribute_name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=False),
    sa.Column('attribute_label', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), nullable=True),
    sa.Column('attribute_type', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), nullable=False),
    sa.Column('attribute_orderby', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), nullable=False),
    sa.Column('attribute_public', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('attribute_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_wc_product_meta_lookup',
    sa.Column('product_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('sku', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), server_default=sa.text("''"), nullable=True),
    sa.Column('global_unique_id', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), server_default=sa.text("''"), nullable=True),
    sa.Column('virtual', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('downloadable', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('min_price', mysql.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('max_price', mysql.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('onsale', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('stock_quantity', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('stock_status', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), server_default=sa.text("'instock'"), nullable=True),
    sa.Column('rating_count', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('average_rating', mysql.DECIMAL(precision=3, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('total_sales', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('tax_status', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), server_default=sa.text("'taxable'"), nullable=True),
    sa.Column('tax_class', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), server_default=sa.text("''"), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('min_max_price', 'wp_wc_product_meta_lookup', ['min_price', 'max_price'], unique=False)
    op.create_table('wp_wc_tax_rate_classes',
    sa.Column('tax_rate_class_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('slug', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('tax_rate_class_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('slug', 'wp_wc_tax_rate_classes', ['slug'], unique=True, mysql_length={'slug': 191})
    op.create_table('wp_term_relationships',
    sa.Column('object_id', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('term_taxonomy_id', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('term_order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('object_id', 'term_taxonomy_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_postmeta',
    sa.Column('meta_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('meta_key', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=True),
    sa.Column('meta_value', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.PrimaryKeyConstraint('meta_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wp_gla_attribute_mapping_rules',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('attribute', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=False),
    sa.Column('source', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), nullable=False),
    sa.Column('category_condition_type', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=10), nullable=False),
    sa.Column('categories', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
