"""Make subdomain nullable in routers

Revision ID: 25d68c6d562a
Revises: f3ead354cef6
Create Date: 2024-09-01 21:55:02.886546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d68c6d562a'
down_revision: Union[str, None] = 'f3ead354cef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routers', 'subdomain',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routers', 'subdomain',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
