"""Update router model to process and store subdomain correctly

Revision ID: 37ec7dc01eb3
Revises: 25d68c6d562a
Create Date: 2024-09-02 01:01:13.139831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37ec7dc01eb3'
down_revision: Union[str, None] = '25d68c6d562a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'routers', ['mac_address'])
    op.create_unique_constraint(None, 'routers', ['serial_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routers', type_='unique')
    op.drop_constraint(None, 'routers', type_='unique')
    # ### end Alembic commands ###
