"""Добавлено поле mac_address в модель Router

Revision ID: 6c2e0865f578
Revises: 025c9c128893
Create Date: 2024-09-01 21:01:13.391484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2e0865f578'
down_revision: Union[str, None] = '025c9c128893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routers', sa.Column('mac_address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routers', 'mac_address')
    # ### end Alembic commands ###
