"""Add config_file_id column to vpn_clients

Revision ID: 9347888b948c
Revises: 37ec7dc01eb3
Create Date: 2024-09-02 05:23:17.425024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9347888b948c'
down_revision: Union[str, None] = '37ec7dc01eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_clients', sa.Column('config_file_id', sa.String(), nullable=True))
    op.drop_column('vpn_clients', 'config_text')
    op.drop_column('vpn_clients', 'config_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_clients', sa.Column('config_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vpn_clients', sa.Column('config_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('vpn_clients', 'config_file_id')
    # ### end Alembic commands ###
