"""add is_for_sale to Router

Revision ID: db708c38802b
Revises: 3c87765431da
Create Date: 2024-09-14 10:25:45.403915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db708c38802b'
down_revision: Union[str, None] = '3c87765431da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routers', sa.Column('is_for_sale', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routers', 'is_for_sale')
    # ### end Alembic commands ###
