"""Add auth_token to Router

Revision ID: dcc6695d092e
Revises: 1a8f7517412b
Create Date: 2024-09-19 23:30:19.708489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc6695d092e'
down_revision: Union[str, None] = '1a8f7517412b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routers', sa.Column('auth_token', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'routers', ['auth_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routers', type_='unique')
    op.drop_column('routers', 'auth_token')
    # ### end Alembic commands ###
