"""Make vpn_config nullable in routers

Revision ID: f3ead354cef6
Revises: 6c2e0865f578
Create Date: 2024-09-01 21:49:06.976261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ead354cef6'
down_revision: Union[str, None] = '6c2e0865f578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routers', 'vpn_config',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routers', 'vpn_config',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
